parameters:
    ejosvp_chart.twig.extension.class: Ejosvp\ChartBundle\Twig\ChartExtension

services:
    ejosvp_chart.twig.extension:
        class: %ejosvp_chart.twig.extension.class%
        arguments:
            - @service_container
        tags:
            - {name: twig.extension}
